% Compute spectrogram

% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 07-Mar-2018 11:35:59

% Parameters
timeLimits = seconds([0 4]); % seconds
frequencyLimits = [0 0.5]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
ts_unnamed_1_ROI = squeeze(ts.Data(:,1));
timeValues = ts.Time;
ts_unnamed_1_ROI = timetable(seconds(timeValues(:)),ts_unnamed_1_ROI,'VariableNames',{'Data'});
ts_unnamed_1_ROI = ts_unnamed_1_ROI(timerange(timeLimits(1),timeLimits(2)),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,T] = pspectrum(ts_unnamed_1_ROI, ...
    'spectrogram', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
